server:
  port: 8089

spring:
    #datasource:
        #name : my_schema
        #url: jdbc:mysql://localhost:3306/my_schema
        #username: root
        #password: root123
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        #filters: stat
        #maxActive: 20
        #initialSize: 1
        #maxWait: 60000
        #minIdle: 1
        #timeBetweenEvictionRunsMillis: 60000
        #minEvictableIdleTimeMillis: 300000
        #validationQuery: select 'x'
        #testWhileIdle: true
        #testOnBorrow: false
        #testOnReturn: false
        #poolPreparedStatements: true
        #maxOpenPreparedStatements: 20
    thymeleaf:
      cache: true
      check-template-location: true
      #content-type: text/html
      enabled: true
      encoding: utf-8
      excluded-view-names:
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
      template-resolver-order:
      view-names:
    #redis配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1s
          max-idle: 8
          min-idle: 0
      timeout: 60s
    data:
      elasticsearch:
        cluster-nodes: 127.0.0.1:9300

#配置多数据源
#localhost
first:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/drizzle
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#aliyun
second:
  datasource:
    jdbc-url: jdbc:mysql://101.132.41.179:3306/aliyun
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  type-aliases-package: com.example.entity

##es地址

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

