server:
  port: 8089

spring:
    datasource:
        name : my_schema
        url: jdbc:mysql://localhost:3306/my_schema
        username: root
        password: root123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
      cache: true
      check-template-location: true
      content-type: text/html
      enabled: true
      encoding: utf-8
      excluded-view-names:
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
      template-resolver-order:
      view-names:
    #redis配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1s
          max-idle: 8
          min-idle: 0
      timeout: 60s


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

